name: Check Broken Links
on: [push]
jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Lychee
      run: cargo install lychee
    - name: Check for broken links
      run: lychee ./**/*.md